### ISSUE TITLE
header row should stick to the top of the screen when scrolling down

### ISSUE THREAD

**Issue by andyras** [TeachTechTaskForce/edumap#119]

**Comment by beccanelson** [comment]
Is there a problem now, or are you just saying you want it to stay fixed at the top of the page?

**Comment by andyras** [comment]
I was saying that I would want it to stick. We had a new person come last
night who wanted to take a crack at this one.

Il giorno mar 5 lug 2016 alle ore 20:11 Becca Nelson <
notifications@github.com> ha scritto:
