### ISSUE TITLE
Contributing to Edumap

### ISSUE THREAD

**Issue by aehrmann** [TeachTechTaskForce/edumap#126]
I'd love to be able to contribute to this project and was wondering if you guys have any sort of process that you'd like people to follow when contributing.

No worries If there's not a completely specified workflow in place, but if anyone has time to reply and possible outline any guidelines you'd  like contributors to follow, I'd greatly appreciate it.

Great presentation on Tuesday (12/6) at Chi Hack Night, by the way!

**Comment by andyras** [comment]
You make a good point: it's hard to know how to contribute just from the README page (a point made in one of the lightning talks on 12/6). I'll consider this issue the prompt to update that page with some more clarity--thanks for that!

It depends on the type of contribution people can make. There are roughly three categories we tend to need help with:
1. web development (includes front and back ends): tweaking frontend appearance/behavior
2. content curation: scraping online lesson plans (manual or scripting) and getting ready for database
3. user design/testing: gathering user feedback, interpreting user tests

I'll add some more specifics when I update the README.

**Comment by andyras** [comment]
README updated at last
