### ISSUE TITLE
remove line between lesson title/description and standards codes

### ISSUE THREAD

**Issue by andyras** [TeachTechTaskForce/edumap#99]
In https://github.com/andyras/edumap/pull/98, a line remains when the accordion is expanded.

**Comment by andyras** [comment]
It may be OK to leave this as long as the standard codes are only revealed on click (accordion).

It is still confusing to have the same line dividing lessons from each other as dividing lesson descriptions from standards codes.

**Comment by datu925** [comment]
@andyras 

Is this still an issue? I don't see a line on current master. I propose closing or adding more information/picture of the unnecessary line.

**Comment by andyras** [comment]
Yes, this was fixed.
